for i=1:20
 importfile('F:\Documents\PyCharmProjects\FLORIStest\mat\2turbs_8.0_0.0_'+string(i*5)+'_dirERR_UAV.mat')
 importfile('F:\Documents\PyCharmProjects\FLORIStest\mat\2turbs_8.0_0.0_'+string(i*5)+'_spdERR_UAV.mat')
end




function importfile(fileToRead1)
%IMPORTFILE(FILETOREAD1)
%  Imports data from the specified file
%  FILETOREAD1:  file to read

%  Auto-generated by MATLAB on 05-Feb-2019 18:46:29

% Import the file
newData1 = load('-mat', fileToRead1);

% Create new variables in the base workspace from those fields.
vars = fieldnames(newData1);
    for i = 1:length(vars)
        assignin('base', vars{i}, newData1.(vars{i}));
    end
end

